services:

    db:
        image: postgres:15.1
        container_name: currency_exchange_db
        ports:
            - "4699:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - currencyExchange
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always

    redis:
        container_name: currency_exchange_redis
        image: redis:5.0.7
        networks:
            - currencyExchange
        ports:
            - "8537:6379"
        restart: always


networks:
    currencyExchange:


volumes:
    postgres_data:
